"""phase2_enrichment_fields

Revision ID: 365ed2c489fc
Revises: cd62b054b90a
Create Date: 2026-07-13 10:36:34.495778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365ed2c489fc'
down_revision: Union[str, Sequence[str], None] = 'cd62b054b90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('kev_listed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('findings', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('findings', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'enriched_at')
    op.drop_column('findings', 'priority_score')
    op.drop_column('findings', 'kev_listed')
    # ### end Alembic commands ###
