"""phase4 incidents

Revision ID: 38f2720323e8
Revises: 3c6fb0be79b1
Create Date: 2026-07-14 10:27:36.197053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f2720323e8'
down_revision: Union[str, Sequence[str], None] = '3c6fb0be79b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('sev1', 'sev2', 'sev3', 'sev4', name='incident_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', name='incident_status_enum'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by', sa.String(length=100), server_default="manual", nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('postmortem', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_timeline_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('note', 'finding_linked', 'runtime_event_linked', 'status_change', name='incident_timeline_entry_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_timeline_entries')
    op.drop_table('incidents')
    # ### end Alembic commands ###
