"""phase3 runtime events

Revision ID: 3c6fb0be79b1
Revises: 365ed2c489fc
Create Date: 2026-07-14 06:12:44.342447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c6fb0be79b1'
down_revision: Union[str, Sequence[str], None] = '365ed2c489fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rule', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('pod_name', sa.String(length=255), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('node', sa.String(length=255), nullable=True),
    sa.Column('k8s_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False, server_default="falco"),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'false_positive', name='runtime_event_status_enum'), nullable=False, server_default="open"),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('services', sa.Column('k8s_namespace', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'k8s_namespace')
    op.drop_table('runtime_events')
    # ### end Alembic commands ###
