"""initial schema

Revision ID: cd62b054b90a
Revises: 
Create Date: 2026-07-13 02:20:59.144153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd62b054b90a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('source_tool', sa.Enum('trivy', 'gitleaks', 'semgrep', 'syft', name='finding_source_enum'), nullable=False),
    sa.Column('category', sa.Enum('secret', 'sast', 'sca', 'iac', 'container', name='finding_category_enum'), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='finding_severity_enum'), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('package_version', sa.String(length=100), nullable=True),
    sa.Column('fixed_version', sa.String(length=100), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'fixed', 'suppressed', 'false_positive', name='finding_status_enum'), nullable=False),
    sa.Column('raw_scanner_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id')
    )
    op.create_index('idx_findings_commit_sha', 'findings', ['commit_sha'], unique=False)
    op.create_index('idx_findings_service', 'findings', ['service'], unique=False)
    op.create_index('idx_findings_service_commit', 'findings', ['service', 'commit_sha'], unique=False)
    op.create_index('idx_findings_severity', 'findings', ['severity'], unique=False)
    op.create_index('idx_findings_status', 'findings', ['status'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier_at_decision', sa.String(length=50), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(), nullable=True),
    sa.Column('override_approved_by', sa.String(length=255), nullable=True),
    sa.Column('override_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_policy_service_commit', 'policy_decisions', ['service', 'commit_sha'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('criticality_tier', sa.Enum('critical', 'standard', 'experimental', name='criticality_tier_enum'), nullable=False),
    sa.Column('environment', sa.Enum('dev', 'prod', name='environment_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_index('idx_policy_service_commit', table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index('idx_findings_status', table_name='findings')
    op.drop_index('idx_findings_severity', table_name='findings')
    op.drop_index('idx_findings_service_commit', table_name='findings')
    op.drop_index('idx_findings_service', table_name='findings')
    op.drop_index('idx_findings_commit_sha', table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
