import os
import requests

from github import Github, Auth

MARKER = "<!-- BLACKBOX_SECURITY_GATE -->"

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
REPOSITORY = os.environ["GITHUB_REPOSITORY"]
PR_NUMBER = int(os.environ["PR_NUMBER"])

GATE_URL = os.environ["GATE_URL"]
GATE_API_KEY = os.environ["GATE_API_KEY"]

SERVICE_NAME = os.environ["SERVICE_NAME"]
COMMIT_SHA = os.environ["COMMIT_SHA"]


def fetch_gate_result():

    response = requests.post(
        f"{GATE_URL}/gate/evaluate",
        headers={
            "X-API-Key": GATE_API_KEY,
            "Content-Type": "application/json",
        },
        json={
            "service": SERVICE_NAME,
            "commit_sha": COMMIT_SHA,
        },
        timeout=30,
    )

    response.raise_for_status()

    return response.json()


def remediation(title: str):

    text = title.lower()

    if "token" in text:
        return "Remove the token and rotate credentials."

    if "secret" in text:
        return "Remove the secret and use a secret manager."

    if "docker" in text:
        return "Run the container as a non-root user."

    if "github-action" in text:
        return "Pin the action to a full commit SHA."

    if "mutable" in text:
        return "Pin the action to a commit SHA."

    if "cve" in text:
        return "Upgrade to a patched package."

    return "Review and remediate."


def build_markdown(result):

    allowed = result["allowed"]

    icon = "✅" if allowed else "❌"

    status = "PASSED" if allowed else "BLOCKED"

    lines = [
        MARKER,
        "",
        f"# {icon} BLACKBOX Security Gate",
        "",
        "| Item | Value |",
        "|------|-------|",
        f"| Decision | {status} |",
        f"| Tier | {result['tier']} |",
        f"| Service | {SERVICE_NAME} |",
        "",
        "---",
        "",
    ]

    violations = result.get("violations", [])

    if not violations:

        lines.append("No policy violations detected.")
        lines.append("")
        lines.append("---")
        lines.append("Generated by BLACKBOX")

        return "\n".join(lines)

    lines.extend([
        "## Findings",
        "",
        "| Severity | Finding | Suggested Remediation |",
        "|----------|---------|-----------------------|",
    ])

    low = []

    for finding in violations:

        severity = finding["severity"].capitalize()

        title = finding["title"]

        fix = remediation(title)

        if severity.lower() in ["low", "info"]:

            low.append((severity, title, fix))

        else:

            lines.append(
                f"| {severity} | {title} | {fix} |"
            )

    if low:

        lines.extend([
            "",
            "<details>",
            "",
            "<summary>Lower Severity Findings</summary>",
            "",
            "| Severity | Finding | Suggested Remediation |",
            "|----------|---------|-----------------------|",
        ])

        for sev, title, fix in low:

            lines.append(
                f"| {sev} | {title} | {fix} |"
            )

        lines.extend([
            "",
            "</details>",
        ])

    lines.extend([
        "",
        "---",
        "",
        "Generated by **BLACKBOX**",
    ])

    return "\n".join(lines)


def find_existing_comment(pr):

    for comment in pr.get_issue_comments():

        if MARKER in comment.body:

            return comment

    return None


def main():

    result = fetch_gate_result()

    body = build_markdown(result)

    auth = Auth.Token(GITHUB_TOKEN)
    github = Github(auth=auth)

    repo = github.get_repo(REPOSITORY)

    pr = repo.get_pull(PR_NUMBER)

    existing = find_existing_comment(pr)

    if existing:

        existing.edit(body)

        print("Updated existing BLACKBOX comment.")

    else:

        pr.create_issue_comment(body)

        print("Created BLACKBOX comment.")


if __name__ == "__main__":
    main()